name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 0.8.0
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter

  path: '>=1.6.4'
  http: '>=0.13.0'
  path_provider: '>=2.0.0'
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.9.0

environment:
  sdk: ">=2.6.0 <3.0.0"


